name: deploy-marketing # descriptive name of workflow

# event to trigger workflow
on:
  push:
    branches: # could be either main or master
      - main
      - master
    paths:
      - 'packages/marketing/**' # This I believe means the action will only run if there are changes to files in this path
      - .github/**

defaults:
  run:
    working-directory: packages/marketing # basically sets the 'working environment' location

jobs:
  build:
    runs-on: ubuntu-latest #linux based virtual machine -

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/marketing/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-2

      # when we update (rather than create) a file, Cloudfront will not automatically make use of it
      # so every time we push, we also want to create the invalidation for the index.html file
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/marketing/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2